version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=production
    depends_on:
      - webhook

  webhook:
    build: .
    command: python webhook.py
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=production
