# Generated by Django 4.2.4 on 2024-11-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, default=None, null=True, unique=True)),
                ('message_id', models.BigIntegerField(blank=True, default=None, null=True, unique=True)),
            ],
        ),
    ]
