# Generated by Django 4.1.2 on 2024-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
