# Generated by Django 4.2.4 on 2024-11-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_posts_category_posts_category_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_users',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
