# Generated by Django 4.2.4 on 2024-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegram_users_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
