# Generated by Django 4.2.4 on 2024-11-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegram_users_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category_pod',
            field=models.CharField(max_length=60),
        ),
    ]
