# Generated by Django 4.2.4 on 2024-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_posts_type_alter_posts_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_users',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
