# Generated by Django 4.1.2 on 2024-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_statics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='static',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
