# Generated by Django 4.2.4 on 2024-12-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_statics_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.JSONField(default=list),
        ),
    ]
