# Generated by Django 4.2.4 on 2024-12-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_posts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
