# Generated by Django 4.2.4 on 2024-12-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_posts_caption_alter_posts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_message_id',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
