# Generated by Django 4.1.2 on 2025-02-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_posts_user_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category_pod_pod',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
